version: '3.8'

services:
  ticket-booking-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./app/src/main/java/ticket/booking/localDB:/app/localDB
    restart: unless-stopped
